services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"

  pipeline:
    build:
      context: .
      dockerfile: Dockerfile.pipeline
    depends_on:
      - api

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "8501:8501"
    depends_on:
      - api